Document: getfastmirror
Title: Debian getfastmirror Manual
Author: <insert document author here>
Abstract: This manual describes what getfastmirror is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/getfastmirror/getfastmirror.sgml.gz

Format: postscript
Files: /usr/share/doc/getfastmirror/getfastmirror.ps.gz

Format: text
Files: /usr/share/doc/getfastmirror/getfastmirror.text.gz

Format: HTML
Index: /usr/share/doc/getfastmirror/html/index.html
Files: /usr/share/doc/getfastmirror/html/*.html
